import { Html, Head, Main, NextScript } from 'next/document'

export default function Document() {
  return (
    <Html lang="en">
      <Head>
        <meta name="description" content="Generated by create next app" />
        <meta
          name="keyword"
          content="Full Stack Seb Develober, Freelancer, MERN developer, Frontend developer"
        />
      </Head>
      <body className="bg-gradient-to-r from-blue-100 to-slate-100 dark:from-dark-500 dark:to-dark-700">
        <Main />
        <NextScript />
      </body>
    </Html>
  );
}
